[package]
name = "kasane"
version = "0.0.2"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
uuid = { version="1.18.1", features = ["v4","serde"]}
tokio = { version = "1.48.0", features = ["full"], optional = true  }
num_cpus = { version = "1.17.0", optional = true }
thiserror = "2.0.17"
redb = { version = "3.1.0", optional = true }
ts-rs = { version = "11.1.0", optional = true }
kasane-logic={path="../kasane-logic"}
once_cell = "1.19"


[lib]
crate-type = ["cdylib"]


[features]
# ストレージ設定
wasm = []            #Wasm上で動作
on-memory = []       #OnMemoryDBとして動作
file = ["dep:redb"]  #redbを用いてファイルに対して書き込み

# 型情報の書き出し
serde = ["dep:serde", "kasane-logic/serde"]
ts-rs = ["dep:ts-rs", "kasane-logic/ts-rs"]
