[package]
name = "kasane"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
kasane-logic = { git = "https://github.com/AirBee-Project/Kasane-Logic.git", branch = "main" ,features = ["openapi","serde"]}
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
utoipa = { version = "5.0", features = ["axum_extras","preserve_order"] }
utoipa-swagger-ui = { version = "9", features = ["axum", "vendored"] }
tower = { version = "0.5.3", features = ["util"] }
redb = "4.1.0"

[dev-dependencies]
http-body-util = "0.1.3"
tempfile = "3.27.0"
