[package]
name = "kasane"
version = "0.0.2"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.141"
schemars = "1.0.4"
logic={path="../logic", features = ["serde_support"]}
ascii = "1.1.0"
wasm-bindgen = "0.2"
once_cell = "1.21.3"


[lib]
crate-type = ["cdylib"]

[features]
default=[]
BuildJsonSchema=[]
