[package]
name = "kasane"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.141"
schemars = "1.0.4"
logic={path="../logic"}

[lib]
crate-type = ["cdylib"]

[features]
default=[]
BuildJsonSchema=[]
