# 開発・テスト用の単一ノード TiKV 設定。

[server]
grpc-concurrency = 1

[storage]
scheduler-worker-pool-size = 1
reserve-space = "0KB"
reserve-raft-space = "0KB"

[storage.block-cache]
capacity = "256MB"

[raftstore]
store-pool-size = 1
apply-pool-size = 1

[readpool.unified]
min-thread-count = 1
max-thread-count = 2

[readpool.storage]
use-unified-pool = true

[readpool.coprocessor]
use-unified-pool = true

[rocksdb]
max-background-jobs = 2
max-sub-compactions = 1

[raftdb]
max-background-jobs = 2
