name: dev
variables:
  - name: baseUrl
    value: 127.0.0.1:5172
    description: ""
  - name: userName
    value: root
    description: ""
  - name: password
    value: password
    description: ""
  - name: accessToken
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290IiwidWlkIjoiMDFhMDY5ZTAtYTY0ZC03OTYzLWEzYzgtOGUxNzc5NzhjNmNlIiwidmVyIjowLCJleHAiOjE3ODg1NjkzNjd9.wst9okZ-WJyoK_26_9LxUl8iybc1DX9fDiy6wMu_4H8
    description: ""
