name: dev
variables:
  - name: baseUrl
    value: http://localhost:5172
  - name: userName
    value: root
  - name: password
    value: password
  - name: accessToken
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJyb290IiwidWlkIjoiMDE5ZmQ0ODQtN2FhNC03OGMwLWJiMDEtMzExODFmMDAwMGExIiwidmVyIjowLCJleHAiOjE3ODYwNjMyODd9.gCHf2nmmbzqZEzicLgkWKsVmpgYS8Gk4J-RTta8evxA
