name: dev
variables:
  - name: baseUrl
    value: http://localhost:5172
  - name: userName
    value: root
  - name: password
    value: password
  # Auth/login を実行すると after-response スクリプトが自動で設定する。
  - name: accessToken
    value: ""
